### ISSUE TITLE
default to no file cycles, with opt-out import

### ISSUE THREAD

**Issue by fommil** [lihaoyi/acyclic#14]
would it be possible to have a version where the plugin enforces no file cycles by default, with an import to opt-out of the check? (which could raise a warning / info level message)

I'd like to use this in the ensime server code, but I don't really want to have to annotate every single file https://github.com/ensime/ensime-server/issues/1148

**Comment by sellout** [comment]
Perhaps a duplicate of #7?

**Comment by fommil** [comment]
I search ticket trackers for dupes, honest! :blush:
