### ISSUE TITLE
Plugin with SBT Not working

### ISSUE THREAD

**Issue by harmeetsingh0013** [lihaoyi/acyclic#22]
I am using acyclic plugin with in sample application as describe in documentation. When i compile my application there is no error or warning generate. [https://github.com/harmeetsingh0013/asyclic-test](Please click on link for looking my sample application)

**Comment by caoilte** [comment]
You added 

```
addCompilerPlugin("com.lihaoyi" %% "acyclic" % "0.1.7")
```

in your `project/plugins.sbt`. It belongs in the `build.sbt`. (This is documented.) 

Suggest close as not a bug.
