### ISSUE TITLE
Support without using import?

### ISSUE THREAD

**Issue by matthughes** [lihaoyi/acyclic#7]
It'd be great if you could run acyclic without putting import acyclic.file into every source file.

**Comment by lihaoyi** [comment]
Yeah it'd be nice to pass in a compiler flag or something. Shouldn't be to
hard either. Want to send a PR? ^_^

**Comment by ziggystar** [comment]
I'm also voting for this issue. It would be nice to have some kind of configuration file that specifies which files/packages must be acyclic.

**Comment by lihaoyi** [comment]
Anyone want to help me implement this? I'll give you commit access in exchange for landing a PR :P :P :P

**Comment by lihaoyi** [comment]
This is now available in 0.1.7

**Comment by fommil** [comment]
how did I miss this? :scream:
